version: "3.2"

services:
  es01:
    image: elasticsearch:7.4.2
    restart: always
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02
    ports:
      - "9200:9200"
      - "9300:9300"

  es02:
    image: elasticsearch:7.4.2
    restart: always
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02

  kibana:
    image: kibana:7.4.2
    restart: always
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      I18N_LOCALE: zh-CN
    ports:
      - "5601:5601"

networks:
  default:
    external:
      name: docker_net