version: '3'
services:
  ftp:
    image: fauria/vsftpd
    container_name: ftp_server
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./data:/home/vsftpd
    environment:
      - FTP_USER=user
      - FTP_PASS=password
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    restart: always
