version: '3'
services:
  ftp:
    image: fauria/vsftpd
    container_name: ftp_server
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - /home/lousuan/workspace/docker/docker-example/data/vsftpd:/home/vsftpd
    environment:
      - FTP_USER=lousuan
      - FTP_PASS=123456
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    restart: always

networks: 
  default:
    external:
      name: docker_net
