version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - 9000:9000
    environment: 
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data