version: '3'

services: 
  jenkins:
    image: mysql:8
    container_name: mysql8
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - LANG=C.UTF-8 
    volumes:
    - ./script:/docker-entrypoint-initdb.d
    - ./config/binlog.cnf:/etc/mysql/conf.d/binlog.cnf
    - ./config/timezone.cnf:/etc/mysql/conf.d/timezone.cnf